# Generated by Django 3.1.1 on 2020-09-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_db',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
